name: Build and Deploy via FTP

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.actor == 'hernan-clich'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Backup remote public_html
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          LFTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          mkdir -p backup
          lftp -e "
            set ssl:verify-certificate no;
            set net:max-retries 2;
            set net:timeout 20;
            open -u $FTP_USER $FTP_HOST;
            mirror /public_html ./backup/public_html;
            bye;
          "
          tar -czf public_html_backup.tar.gz -C backup public_html

      - name: Deploy via FTP
        id: deploy
        continue-on-error: true
        uses: SamKirkland/FTP-Deploy-Action@a51268f67f6605236975928ae28b0f7e9971d50a
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          security: loose
          concurrency: 1
          local-dir: ./build/
          server-dir: /public_html/
          timeout: 1800
          dangerous-clean-slate: false

      - name: Restore backup if deploy failed
        if: failure() && steps.deploy.outcome == 'failure'
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          LFTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          tar -xzf public_html_backup.tar.gz
          lftp -e "
            set ssl:verify-certificate no;
            set net:max-retries 2;
            set net:timeout 20;
            open -u $FTP_USER $FTP_HOST;
            mirror -R ./backup/public_html /public_html;
            bye;
          "
